### ISSUE TITLE
Awesome list

### ISSUE THREAD

**Issue by dereuromark** [ciricihq/cake-adminlte#5]
Sounds like sth that could be added to the https://github.com/FriendsOfCake/awesome-cakephp for others to more easily find and use it.

**Comment by dereuromark** [comment]
But please use MIT license in that case.

**Comment by elboletaire** [comment]
Sorry but why the license change?

**Comment by dereuromark** [comment]
As per https://github.com/FriendsOfCake/awesome-cakephp/blob/master/CONTRIBUTING.md 
Using a copyleft license is usually a bad idea, as it discourages real use of it in proprietary products.

**Comment by elboletaire** [comment]
Ok so the problem is due to the usage with proprietary products. If I'm not wrong, using a LGPL instead of a GPL license should be enough, right?

**Comment by dereuromark** [comment]
Not sure.. If you dont mind, just use MIT. That is the safest and easiest one for you and all others :)

**Comment by dereuromark** [comment]
Btw: I do have a few additions here as we use the same template for a project too.
Maybe they can then be added more easily with the same license.

**Comment by elboletaire** [comment]
Taking a look at https://choosealicense.com/licenses/ I can see that I was wrong: both the GPL and LGPL have the `Disclose source` condition, so I understand none of these fit with what you're saying.

BTW, in your contributing guidelines you say we have to use an open source license (preferably MIT), but that means we can still publish this plugin to the awesome list, due to the fact that we already have an OS license, right?

> Not sure.. If you dont mind, just use MIT. That is the safest and easiest one for you and all others :)

If I'm discussing this here is because we really mind it. At @ciricihq and at @alvarium we decided to use the GPL license because we love open source, and the GPL is probably the best license to promote open source coding. Using an Apache or MIT license may be great for my plugins visibility or their acceptance (specially by enterprises), but that's not something we care for.

We want to promote open source coding, and we think that using the GPL license is a great way to do it.

Also, the license limitations are something related to making changes to the code. But this plugin can be used without making any changes to it, so the license should not be a problem for the majority of use cases.

Said that, we'll think about changing this plugin license, but I can't promise anything. As said, we care more about Open Source than "making CakePHP great again" (sorry for the joke).

**Comment by dereuromark** [comment]
> and the GPL is probably the best license to promote open source coding.

Thats where you are actually dead wrong.
Because when looking into using the plugin, the only ones who will actually then use it are open source repos (which to be honest is the minority of em).
So you are excluding all company and non-non-profit orgs from using it due to the nonsense disclosre phrase :) As our lawers discussed that in detail I can confirm with 100% certainty that this is a no go for most companies you can take serious in terms of legal support.
They simply do not want to have to disclose any of their code just because they are also using some open source tool.

So by limiting the scope here you are shooting yourself in the foot as the majority will simply ignore your code and look otherwise for a solution. So you are as a result missing out on the majority of users and thus potential contributors to your tool, killing the open source spirit with it completely :)

So careful, sometimes being less restrictive is the better option.

**Comment by dereuromark** [comment]
To be clear: Just because people can modify and use it in any form without contributing back, most actually will contribute back in order to not have to work on a forked version over time.
So the fear here from your side is not justified.

> (specially by enterprises), but that's not something we care for

Thats a strange attitude IMO.
Those should actually be the ones you should have your main care for, since those are the ones with the resources to conribute back (the bigger the more money the more resources the more time per developer to open source usually).
Small open source coders usually do not have too much time here. They are not dependent enough on what they decided for.

**Comment by dereuromark** [comment]
I am closing this now as I did my part :) Rest is up to you guys.

**Comment by elboletaire** [comment]
@dereuromark Ok thanks Mark! As said, we need to discuss this internally at @ciricihq and @alvarium.

Thank you very much for your comments :)
